#!/usr/bin/env python3
"""Draw the DMG install window's background, at 1x and 2x, and combine them.

The first screen anyone sees after downloading Marlo carried the old product
name for eleven releases. Every text file in the app had been renamed and a
guard watched them; this text was baked into a committed PNG, where no check
could read it and no diff could show it.

So the words live here, in a file check_branding.py scans, and the image is a
build product rather than a binary someone has to remember to redraw. That is
the whole point of this script — the picture is incidental.

Run it directly to refresh the committed assets:

    python3 packaging/make_dmg_background.py

build_dmg.sh calls it too, and falls back to the committed .tiff when Pillow is
absent (the committed one is generated by this script, so the two agree).

The .tiff is what Finder actually reads: `tiffutil -cathidpicheck` packs the 1x
and 2x images into one multi-representation file, which is how the window stays
sharp on a Retina display without shipping a 2x image to everyone.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# The strings. This is why the file exists.
TITLE = "Install Marlo"
SUBTITLE = "Drag the app onto the Applications folder"

W, H = 640, 400
BG = (247, 248, 250)
INK = (44, 48, 56)
MUTED = (140, 147, 158)
ACCENT = (46, 104, 232)

# Pillow's "a" anchor is the font's ascender, which sits above the tallest
# glyph by the face's internal leading — these are tuned so the rendered ink
# lands on the same rows as the design it replaces (title 55-73, subtitle
# 88-97), not so they read as nice round numbers.
TITLE_ANCHOR_Y = 48
SUB_ANCHOR_Y = 85
ARROW_Y = 190
ARROW_X0, ARROW_X1 = 262, 379

# macOS ships these; the app's own UI is set in the same family.
FONTS = [
    ("/System/Library/Fonts/HelveticaNeue.ttc", 0),
    ("/System/Library/Fonts/Helvetica.ttc", 0),
    ("/System/Library/Fonts/SFNS.ttf", None),
]


def _font(size: int, bold: bool):
    from PIL import ImageFont

    for path, index in FONTS:
        if not Path(path).exists():
            continue
        try:
            # HelveticaNeue.ttc: 0 is Regular, 1 is Bold in the collection order
            # Apple ships. A missing face is not worth failing a build over.
            idx = (1 if bold else 0) if index is not None else 0
            return ImageFont.truetype(path, size, index=idx)
        except Exception:
            continue
    return ImageFont.load_default()


def render(scale: int):
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (W * scale, H * scale), BG)
    d = ImageDraw.Draw(img)

    title_font = _font(24 * scale, bold=True)
    sub_font = _font(11 * scale, bold=False)

    d.text(
        (W * scale / 2, TITLE_ANCHOR_Y * scale),
        TITLE,
        font=title_font,
        fill=INK,
        anchor="ma",
    )
    d.text(
        (W * scale / 2, SUB_ANCHOR_Y * scale),
        SUBTITLE,
        font=sub_font,
        fill=MUTED,
        anchor="ma",
    )

    # The arrow the two icons sit either side of. build_dmg.sh places them at
    # y≈190, so this line and those coordinates have to move together.
    y = ARROW_Y * scale
    d.line(
        [(ARROW_X0 * scale, y), ((ARROW_X1 - 8) * scale, y)],
        fill=ACCENT,
        width=max(1, round(1.5 * scale)),
    )
    head = 6 * scale
    d.polygon(
        [
            (ARROW_X1 * scale, y),
            ((ARROW_X1 - head) * scale // 1, y - head // 1),
            ((ARROW_X1 - head) * scale // 1, y + head // 1),
        ],
        fill=ACCENT,
    )
    return img


def main() -> int:
    try:
        import PIL  # noqa: F401
    except ImportError:
        print(
            "Pillow not installed — leaving the committed dmg-background.* in place",
            file=sys.stderr,
        )
        return 0

    one = HERE / "dmg-background.png"
    two = HERE / "dmg-background@2x.png"
    render(1).save(one)
    render(2).save(two)

    tiffutil = shutil.which("tiffutil")
    if not tiffutil:
        print("tiffutil not found (non-macOS?) — .tiff not rebuilt", file=sys.stderr)
        return 0

    out = HERE / "dmg-background.tiff"
    subprocess.run(
        [tiffutil, "-cathidpicheck", str(one), str(two), "-out", str(out)],
        check=True,
        capture_output=True,
    )
    print(f"dmg background: {TITLE!r} → {out.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
